<?php
return [
    'protocol'=>'Thank you for choosing KongQi Laravel admin, and hope that our efforts can provide you with a simple, efficient, and excellent general background. <br/>

Notice to users: This agreement is a legal agreement between you and Haoxue Technology regarding your use of KongQi Laravel admin products and services. Regardless of whether you are an individual or an organization, whether it is profitable, or how it is used (including for the purpose of learning and research), you need to read this agreement carefully, including the exemption clauses that exempt or limit the responsibility of Haoxue Technology and the restrictions on your rights. Please review and accept or not accept these terms of service. If you do not agree to these terms of service and Haoxue Technology\'s modification at any time, you should not use or actively cancel KongQi Laravel admin products. Otherwise, any registration, login, downloading, viewing, etc. of your use of KongQi Laravel admin\'s related services will be deemed to be your complete acceptance of the terms of service, including any modifications made by Haoxue Technology to the terms of service at any time. <br/>

Once the terms of service are changed, Haoxue Technology will announce the revised content on the official website. Once the revised terms of service are published on the website, they will effectively replace the original terms of service. You can visit the official website at any time to check the latest version of the terms of service. If you choose to accept these terms, you agree to be bound by the conditions of the agreement. If you do not agree to the terms of service, you cannot obtain the right to use the service. If you violate the provisions of this article, Haoxue Technology has the right to suspend or terminate your use of KongQi Laravel admin products at any time and reserves the right to pursue related legal responsibilities. <br/>

After understanding, agreeing, and observing all the terms of this agreement, you can start using KongQi Laravel admin products. You may also directly sign another written agreement with Haoxue Technology to supplement or replace all or any part of this agreement. <br/>

In addition to the system template, Haoxue Technology has all the intellectual property rights of KongQi Laravel admin, including trademarks and copyrights. You have the right to use, copy, modify, merge, publish, distribute, reauthorize, and sell software and copies of software, but you need to modify the authorization terms to the appropriate content, and must include a copyright statement and a license statement'
];
